version: '3'
services:
  db:
    container_name: srv-mysql
    image: jorarmarfin/mysql:5.7-moodle-4.0.4
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/backup
    restart: always
  adminer:
    container_name: srv-adminer
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always