version: '3'
services:
  db:
    container_name: srv-mysql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS_MYSQL}
    volumes:
      - ${MYSQL_FILES}:/var/lib/mysql
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d
    restart: always
  adminer:
    container_name: srv-adminer
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always