version: '3'
services:
  db:
    container_name: srv-mysql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS_MYSQL}
    volumes:
      - ${FILES}:/var/lib/mysql
      - ${CONFIG}:/etc/mysql/conf.d
    networks:
      - red-trabajo
    restart: always